library(shiny)
library(shinydashboard)
library(maps)
library(dplyr)
library(leaflet)
library(ggplot2)
library(tidyverse)
library(DT)
library(plotly)
library(corrplot)
library(caret)
library(stargazer)
library(MASS)
library(caTools)
library(broom)

source("a5.server.R")
source("a5.ui.R")
shinyApp(ui = ui, server = server)